// playground/solidjs/src/App.tsx
import { createSignal, createMemo, For, Show } from 'solid-js'
import { searchDistricts, getCityArray, getDistrictArray } from '@simoko/tw-zip'
import {
  getAreas6,
  getCities6,
  getRoads6,
  getZipCode6,
  searchRoads6,
} from '@simoko/tw-zip/zip6'
import { useTwZip6 as useTwZip6Lazy } from '@simoko/tw-zip/solidjs/lazy'

function App() {
  // 3 碼
  const cities = getCityArray()
  const [city, setCity] = createSignal(cities[0])
  const districts = createMemo(() => getDistrictArray(city()))
  const [zipCode, setZipCode] = createSignal(districts()[0]?.value ?? '')
  const district = createMemo(() => districts().find(d => d.value === zipCode())?.label ?? '')
  const [searchKeyword, setSearchKeyword] = createSignal('')
  const searchResults = createMemo(() =>
    searchKeyword().trim() ? searchDistricts(searchKeyword()) : []
  )

  const handleCityChange = (value: string) => {
    setCity(value)
    const ds = getDistrictArray(value)
    setZipCode(ds[0]?.value ?? '')
  }

  const handleDistrictChange = (label: string) => {
    const found = districts().find(d => d.label === label)
    if (found) setZipCode(found.value)
  }

  const selectFromSearch = (c: string, d: string) => {
    handleCityChange(c)
    handleDistrictChange(d)
    setSearchKeyword('')
  }

  // 6 碼
  const cities6 = getCities6()
  const [city6, setCity6] = createSignal('')
  const [area6, setArea6] = createSignal('')
  const [road6, setRoad6] = createSignal('')
  const [number6, setNumber6] = createSignal('')
  const [searchRoad, setSearchRoad] = createSignal('')

  const areas6 = createMemo(() => city6() ? getAreas6(city6()) : [])
  const roads6 = createMemo(() => city6() && area6() ? getRoads6(city6(), area6()) : [])

  const zip6Result = createMemo(() => {
    if (!city6() || !area6() || !road6()) return null
    return getZipCode6({
      city: city6(),
      area: area6(),
      road: road6(),
      number: number6() ? Number(number6()) : undefined,
    })
  })

  const roadSearchResults = createMemo(() =>
    searchRoad().trim()
      ? searchRoads6(searchRoad(), city6() || undefined, area6() || undefined).slice(0, 10)
      : []
  )

  const handleCity6Change = (value: string) => {
    setCity6(value)
    setArea6('')
    setRoad6('')
  }

  const handleArea6Change = (value: string) => {
    setArea6(value)
    setRoad6('')
  }

  const selectRoad = (r: { city: string; area: string; road: string }) => {
    setCity6(r.city)
    setArea6(r.area)
    setRoad6(r.road)
    setSearchRoad('')
  }

  return (
    <div class="container">
      <h1>@simoko/tw-zip</h1>
      <p class="subtitle">台灣縣市、行政區、郵遞區號選擇器</p>

      {/* 3 碼區塊 */}
      <section class="section">
        <h2>3 碼郵遞區號</h2>

        <div class="selector-group">
          <div class="selector">
            <label>縣市</label>
            <select value={city()} onChange={e => handleCityChange(e.target.value)}>
              <For each={cities}>{c => <option value={c}>{c}</option>}</For>
            </select>
          </div>

          <div class="selector">
            <label>行政區</label>
            <select value={district()} onChange={e => handleDistrictChange(e.target.value)}>
              <For each={districts()}>{d => <option value={d.label}>{d.label}</option>}</For>
            </select>
          </div>
        </div>

        <div class="result">
          <div class="result-item">
            <span class="label">郵遞區號</span>
            <span class="value zipcode">{zipCode()}</span>
          </div>
          <div class="result-item">
            <span class="label">完整地址</span>
            <span class="value">{zipCode()} {city()}{district()}</span>
          </div>
        </div>

        {/* 行政區搜尋 */}
        <div class="search-section">
          <label>搜尋行政區</label>
          <input
            type="text"
            placeholder="輸入關鍵字，例如：中正"
            value={searchKeyword()}
            onInput={e => setSearchKeyword(e.target.value)}
          />
          <Show when={searchResults().length > 0}>
            <ul class="search-results">
              <For each={searchResults().slice(0, 8)}>
                {([zip, c, d]) => (
                  <li onClick={() => selectFromSearch(c, d)}>
                    <span class="zip">{zip}</span> {c} {d}
                  </li>
                )}
              </For>
            </ul>
          </Show>
        </div>
      </section>

      {/* 6 碼區塊 */}
      <section class="section">
        <h2>6 碼郵遞區號 (3+3)</h2>

        <div class="selector-group">
          <div class="selector">
            <label>縣市</label>
            <select value={city6()} onChange={e => handleCity6Change(e.target.value)}>
              <option value="">請選擇</option>
              <For each={cities6}>{c => <option value={c}>{c}</option>}</For>
            </select>
          </div>

          <div class="selector">
            <label>行政區</label>
            <select value={area6()} onChange={e => handleArea6Change(e.target.value)} disabled={!city6()}>
              <option value="">請選擇</option>
              <For each={areas6()}>{a => <option value={a}>{a}</option>}</For>
            </select>
          </div>

          <div class="selector">
            <label>路名</label>
            <select value={road6()} onChange={e => setRoad6(e.target.value)} disabled={!area6()}>
              <option value="">請選擇</option>
              <For each={roads6()}>{r => <option value={r}>{r}</option>}</For>
            </select>
          </div>

          <div class="selector small">
            <label>門牌</label>
            <input
              type="number"
              placeholder="號"
              value={number6()}
              onInput={e => setNumber6(e.target.value)}
              disabled={!road6()}
            />
          </div>
        </div>

        <Show when={zip6Result()}>
          {result => (
            <div class="result">
              <div class="result-item">
                <span class="label">6 碼郵遞區號</span>
                <span class="value zipcode">{result().zipcode}</span>
              </div>
              <div class="result-item">
                <span class="label">完整地址</span>
                <span class="value">
                  {result().zipcode} {result().city}{result().area}{result().road}{number6() ? `${number6()}號` : ''}
                </span>
              </div>
            </div>
          )}
        </Show>

        {/* 路名搜尋 */}
        <div class="search-section">
          <label>搜尋路名</label>
          <input
            type="text"
            placeholder="輸入關鍵字，例如：忠孝東路"
            value={searchRoad()}
            onInput={e => setSearchRoad(e.target.value)}
          />
          <Show when={roadSearchResults().length > 0}>
            <ul class="search-results">
              <For each={roadSearchResults()}>
                {r => (
                  <li onClick={() => selectRoad(r)}>
                    {r.city} {r.area} <strong>{r.road}</strong>
                  </li>
                )}
              </For>
            </ul>
          </Show>
        </div>
      </section>

      <Zip6LazySection />

      <a
        class="github-link"
        href="https://github.com/supra126/tw-zip"
        target="_blank"
        rel="noopener noreferrer"
      >
        GitHub
      </a>
    </div>
  )
}

function Zip6LazySection() {
  const lazy = useTwZip6Lazy()

  return (
    <section class="section">
      <h2>6 碼 Lazy Load {lazy.loading() && <span style={{ "font-size": '0.8rem', color: '#999' }}>(載入中...)</span>}</h2>

      <div class="selector-group">
        <div class="selector">
          <label>縣市</label>
          <select value={lazy.city()} onChange={e => lazy.setCity(e.target.value)} disabled={lazy.loading()}>
            <option value="">請選擇</option>
            <For each={lazy.cities()}>{c => <option value={c}>{c}</option>}</For>
          </select>
        </div>

        <div class="selector">
          <label>行政區</label>
          <select value={lazy.area()} onChange={e => lazy.setArea(e.target.value)} disabled={lazy.loading() || !lazy.city()}>
            <option value="">請選擇</option>
            <For each={lazy.areas()}>{a => <option value={a}>{a}</option>}</For>
          </select>
        </div>

        <div class="selector">
          <label>路名</label>
          <select value={lazy.road()} onChange={e => lazy.setRoad(e.target.value)} disabled={lazy.loading() || !lazy.area()}>
            <option value="">請選擇</option>
            <For each={lazy.roads()}>{r => <option value={r}>{r}</option>}</For>
          </select>
        </div>

        <div class="selector small">
          <label>門牌</label>
          <input
            type="number"
            placeholder="號"
            value={lazy.number() ?? ''}
            onInput={e => lazy.setNumber(e.target.value ? Number(e.target.value) : undefined)}
            disabled={lazy.loading() || !lazy.road()}
          />
        </div>
      </div>

      <Show when={lazy.result()}>
        {result => (
          <div class="result">
            <div class="result-item">
              <span class="label">6 碼郵遞區號</span>
              <span class="value zipcode">{lazy.zipCode()}</span>
            </div>
            <div class="result-item">
              <span class="label">完整地址</span>
              <span class="value">
                {result().zipcode} {result().city}{result().area}{result().road}{lazy.number() ? `${lazy.number()}號` : ''}
              </span>
            </div>
          </div>
        )}
      </Show>

      <p style={{ "font-size": '0.75rem', color: '#888', "margin-top": '0.5rem' }}>
        資料按縣市動態載入，初始僅 ~5KB
      </p>
    </section>
  )
}

export default App

// playground/angular/src/app/app.component.ts
import { Component, computed, inject, OnInit, signal } from '@angular/core'
import { CommonModule } from '@angular/common'
import { searchDistricts, getCityArray, getDistrictArray } from '@simoko/tw-zip'
import {
  getAreas6,
  getCities6,
  getRoads6,
  getZipCode6,
  searchRoads6,
} from '@simoko/tw-zip/zip6'
import { TwZip6LazyService } from '@simoko/tw-zip/angular/lazy'

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="container">
      <h1>&#64;simoko/tw-zip</h1>
      <p class="subtitle">台灣縣市、行政區、郵遞區號選擇器</p>

      <!-- 3 碼區塊 -->
      <section class="section">
        <h2>3 碼郵遞區號</h2>

        <div class="selector-group">
          <div class="selector">
            <label>縣市</label>
            <select [value]="city()" (change)="setCity($any($event.target).value)">
              <option *ngFor="let c of cities" [value]="c">{{ c }}</option>
            </select>
          </div>

          <div class="selector">
            <label>行政區</label>
            <select [value]="district()" (change)="setDistrict($any($event.target).value)">
              <option *ngFor="let d of districts()" [value]="d.label">{{ d.label }}</option>
            </select>
          </div>
        </div>

        <div class="result">
          <div class="result-item">
            <span class="label">郵遞區號</span>
            <span class="value zipcode">{{ zipCode() }}</span>
          </div>
          <div class="result-item">
            <span class="label">完整地址</span>
            <span class="value">{{ zipCode() }} {{ city() }}{{ district() }}</span>
          </div>
        </div>

        <!-- 行政區搜尋 -->
        <div class="search-section">
          <label>搜尋行政區</label>
          <input
            type="text"
            placeholder="輸入關鍵字，例如：中正"
            [value]="searchKeyword()"
            (input)="searchKeyword.set($any($event.target).value)"
          />
          <ul *ngIf="searchResults().length > 0" class="search-results">
            <li
              *ngFor="let r of searchResults().slice(0, 8)"
              (click)="selectFromSearch(r[1], r[2])"
            >
              <span class="zip">{{ r[0] }}</span> {{ r[1] }} {{ r[2] }}
            </li>
          </ul>
        </div>
      </section>

      <!-- 6 碼區塊 -->
      <section class="section">
        <h2>6 碼郵遞區號 (3+3)</h2>

        <div class="selector-group">
          <div class="selector">
            <label>縣市</label>
            <select [value]="city6()" (change)="setCity6($any($event.target).value)">
              <option value="">請選擇</option>
              <option *ngFor="let c of cities6" [value]="c">{{ c }}</option>
            </select>
          </div>

          <div class="selector">
            <label>行政區</label>
            <select [value]="area6()" (change)="setArea6($any($event.target).value)" [disabled]="!city6()">
              <option value="">請選擇</option>
              <option *ngFor="let a of areas6()" [value]="a">{{ a }}</option>
            </select>
          </div>

          <div class="selector">
            <label>路名</label>
            <select [value]="road6()" (change)="road6.set($any($event.target).value)" [disabled]="!area6()">
              <option value="">請選擇</option>
              <option *ngFor="let r of roads6()" [value]="r">{{ r }}</option>
            </select>
          </div>

          <div class="selector small">
            <label>門牌</label>
            <input
              type="number"
              placeholder="號"
              [value]="number6()"
              (input)="number6.set($any($event.target).value)"
              [disabled]="!road6()"
            />
          </div>
        </div>

        <div *ngIf="zip6Result()" class="result">
          <div class="result-item">
            <span class="label">6 碼郵遞區號</span>
            <span class="value zipcode">{{ zip6Result()?.zipcode }}</span>
          </div>
          <div class="result-item">
            <span class="label">完整地址</span>
            <span class="value">
              {{ zip6Result()?.zipcode }} {{ zip6Result()?.city }}{{ zip6Result()?.area }}{{ zip6Result()?.road }}{{ number6() ? number6() + '號' : '' }}
            </span>
          </div>
        </div>

        <!-- 路名搜尋 -->
        <div class="search-section">
          <label>搜尋路名</label>
          <input
            type="text"
            placeholder="輸入關鍵字，例如：忠孝東路"
            [value]="searchRoad()"
            (input)="searchRoad.set($any($event.target).value)"
          />
          <ul *ngIf="roadSearchResults().length > 0" class="search-results">
            <li *ngFor="let r of roadSearchResults()" (click)="selectRoad(r)">
              {{ r.city }} {{ r.area }} <strong>{{ r.road }}</strong>
            </li>
          </ul>
        </div>
      </section>

      <!-- 6 碼 Lazy Load 區塊 -->
      <section class="section">
        <h2>6 碼 Lazy Load <span *ngIf="lazyService.loading()" style="font-size: 0.8rem; color: #999">(載入中...)</span></h2>

        <div class="selector-group">
          <div class="selector">
            <label>縣市</label>
            <select [value]="lazyService.city()" (change)="onLazyCityChange($any($event.target).value)" [disabled]="lazyService.loading()">
              <option value="">請選擇</option>
              <option *ngFor="let c of lazyService.cities()" [value]="c">{{ c }}</option>
            </select>
          </div>

          <div class="selector">
            <label>行政區</label>
            <select [value]="lazyService.area()" (change)="lazyService.setArea($any($event.target).value)" [disabled]="lazyService.loading() || !lazyService.city()">
              <option value="">請選擇</option>
              <option *ngFor="let a of lazyService.areas()" [value]="a">{{ a }}</option>
            </select>
          </div>

          <div class="selector">
            <label>路名</label>
            <select [value]="lazyService.road()" (change)="lazyService.setRoad($any($event.target).value)" [disabled]="lazyService.loading() || !lazyService.area()">
              <option value="">請選擇</option>
              <option *ngFor="let r of lazyService.roads()" [value]="r">{{ r }}</option>
            </select>
          </div>

          <div class="selector small">
            <label>門牌</label>
            <input
              type="number"
              placeholder="號"
              [value]="lazyService.number() ?? ''"
              (input)="onLazyNumberChange($any($event.target).value)"
              [disabled]="lazyService.loading() || !lazyService.road()"
            />
          </div>
        </div>

        <div *ngIf="lazyService.result()" class="result">
          <div class="result-item">
            <span class="label">6 碼郵遞區號</span>
            <span class="value zipcode">{{ lazyService.zipCode() }}</span>
          </div>
          <div class="result-item">
            <span class="label">完整地址</span>
            <span class="value">
              {{ lazyService.result()?.zipcode }} {{ lazyService.result()?.city }}{{ lazyService.result()?.area }}{{ lazyService.result()?.road }}{{ lazyService.number() ? lazyService.number() + '號' : '' }}
            </span>
          </div>
        </div>

        <p style="font-size: 0.75rem; color: #888; margin-top: 0.5rem">
          資料按縣市動態載入，初始僅 ~5KB
        </p>
      </section>

      <a
        class="github-link"
        href="https://github.com/supra126/tw-zip"
        target="_blank"
        rel="noopener noreferrer"
      >
        GitHub
      </a>
    </div>
  `,
})
export class AppComponent implements OnInit {
  readonly lazyService = inject(TwZip6LazyService)
  // 3 碼
  cities = getCityArray()
  city = signal(this.cities[0])
  districts = computed(() => getDistrictArray(this.city()))
  zipCode = signal(this.districts()[0]?.value ?? '')
  district = computed(() => this.districts().find(d => d.value === this.zipCode())?.label ?? '')
  searchKeyword = signal('')
  searchResults = computed(() =>
    this.searchKeyword().trim() ? searchDistricts(this.searchKeyword()) : []
  )

  setCity(value: string) {
    this.city.set(value)
    const ds = getDistrictArray(value)
    this.zipCode.set(ds[0]?.value ?? '')
  }

  setDistrict(label: string) {
    const found = this.districts().find(d => d.label === label)
    if (found) this.zipCode.set(found.value)
  }

  selectFromSearch(c: string, d: string) {
    this.setCity(c)
    this.setDistrict(d)
    this.searchKeyword.set('')
  }

  // 6 碼
  cities6 = getCities6()
  city6 = signal('')
  area6 = signal('')
  road6 = signal('')
  number6 = signal('')
  searchRoad = signal('')

  areas6 = computed(() => this.city6() ? getAreas6(this.city6()) : [])
  roads6 = computed(() => this.city6() && this.area6() ? getRoads6(this.city6(), this.area6()) : [])

  zip6Result = computed(() => {
    if (!this.city6() || !this.area6() || !this.road6()) return null
    return getZipCode6({
      city: this.city6(),
      area: this.area6(),
      road: this.road6(),
      number: this.number6() ? Number(this.number6()) : undefined,
    })
  })

  roadSearchResults = computed(() =>
    this.searchRoad().trim()
      ? searchRoads6(this.searchRoad(), this.city6() || undefined, this.area6() || undefined).slice(0, 10)
      : []
  )

  setCity6(value: string) {
    this.city6.set(value)
    this.area6.set('')
    this.road6.set('')
  }

  setArea6(value: string) {
    this.area6.set(value)
    this.road6.set('')
  }

  selectRoad(r: { city: string; area: string; road: string }) {
    this.city6.set(r.city)
    this.area6.set(r.area)
    this.road6.set(r.road)
    this.searchRoad.set('')
  }

  // Lazy Load
  ngOnInit() {
    this.lazyService.init()
  }

  onLazyCityChange(value: string) {
    this.lazyService.setCity(value)
  }

  onLazyNumberChange(value: string) {
    this.lazyService.setNumber(value ? Number(value) : undefined)
  }
}
